<?php
/*
* Implementation of hook_menu
*/

function products_menu()
{

$items['admin/config/products'] = array(
'title' => 'Product settings of admin',
'description' => 'Adjust the settings of products',
'position' => 'left',
'weight' => -5,
'page callback' => 'system_admin_menu_block_page',
'access arguments' => array('administer site configuration'),
'file' => 'system.admin.inc',
'file path' => drupal_get_path('module', 'system'),
);

$items['admin/config/products/add_setting'] = array(
'title' => 'products adding',
'description' => 'Control who can add products',
'page callback' => 'drupal_get_form',
'page arguments' => array('products_admin_settings'),
'access arguments' => array('administer site configuration'),
'type' => MENU_NORMAL_ITEM,
'file' => 'products.admin.inc',
);
$items['admin/config/products/edit_setting'] = array(
'title' => 'products edit',
'description' => 'Control who can edit products',
'page callback' => 'drupal_get_form',
'page arguments' => array('products_admin_settings'),
'access arguments' => array('administer site configuration'),
'type' => MENU_NORMAL_ITEM,
'file' => 'products.admin.inc',
);
$items['admin/config/products/remove_setting'] = array(
'title' => 'products remove',
'description' => 'Control who can remove products',
'page callback' => 'drupal_get_form',
'page arguments' => array('products_admin_settings'),
'access arguments' => array('administer site configuration'),
'type' => MENU_NORMAL_ITEM,
'file' => 'products.admin.inc',
);
return $items;

}